---
name: Format source via black
# This workflow is triggered on pull requests to the repository.
on: [pull_request]

jobs:
  build:
    # Job name is Greeting
    name: Black Format
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Black Code Formatter
        uses: lgeiger/black-action@v1.0.1
        with:
          args: ". --check"
